title: 'Tiernans Comms Closet'
description: Dont Ask
permalink:     /:title/
highlighter:   true
email:	tiernan@tiernanotoole.ie
baseurl: ""
markdown: kramdown
twitter_username: tiernano
github_username:  tiernano 
url: "http://blog.lotas-smartman.net"
paginate: 5
plugins: 
  -  jekyll-paginate


